Add C++20's std::span backport
jakalope/jakalib pull request #4
Opened 2019-12-05 18:18 UTC by darrinwillis

Add std::span from https://github.com/tcbrindle/span with a trivial test to ensure it compiles. Also places the span impl under namespace `jakalib` for consistency.

2019-12-06 03:59 UTC, jakalope requested changes

2019-12-06 03:59 UTC, jakalope commented on include/jakalib/span.h
> +#define TCB_SPAN_NAMESPACE_NAME tcb
define as `jakalib`, please

2019-12-06 04:09 UTC, darrinwillis commented on include/jakalib/span.h
> +#define TCB_SPAN_NAMESPACE_NAME tcb
Ah whoops; had it specified twice.

2019-12-07 01:58 UTC, jakalope approved these changes

2019-12-07 01:58 UTC, merged